// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChwiW4RjKeZR_caPJipwKGMSLtILv7g_c',
    appId: '1:377990185064:android:f1b29f41e23f90ca7cbbdd',
    messagingSenderId: '377990185064',
    projectId: 'getpaid-ea9e5',
    storageBucket: 'getpaid-ea9e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25I-bnrTwv54rlE_JDU2Y6pDs5ld99LA',
    appId: '1:377990185064:ios:05a69199a6905e267cbbdd',
    messagingSenderId: '377990185064',
    projectId: 'getpaid-ea9e5',
    storageBucket: 'getpaid-ea9e5.appspot.com',
    iosClientId:
        '377990185064-hf0cr5hlmajilvvllfsv5jajnej8rt0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.getPaid',
  );
}
